# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/filippo/Desktop/intrinsically_stable_mpc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/filippo/Desktop/intrinsically_stable_mpc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filippo/Desktop/intrinsically_stable_mpc/CMakeFiles /home/filippo/Desktop/intrinsically_stable_mpc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filippo/Desktop/intrinsically_stable_mpc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named osgAtlasSimbicon

# Build rule for target.
osgAtlasSimbicon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgAtlasSimbicon
.PHONY : osgAtlasSimbicon

# fast build rule for target.
osgAtlasSimbicon/fast:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/build
.PHONY : osgAtlasSimbicon/fast

Controller.o: Controller.cpp.o

.PHONY : Controller.o

# target to build an object file
Controller.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/Controller.cpp.o
.PHONY : Controller.cpp.o

Controller.i: Controller.cpp.i

.PHONY : Controller.i

# target to preprocess a source file
Controller.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/Controller.cpp.i
.PHONY : Controller.cpp.i

Controller.s: Controller.cpp.s

.PHONY : Controller.s

# target to generate assembly for a file
Controller.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/Controller.cpp.s
.PHONY : Controller.cpp.s

MPCSolver.o: MPCSolver.cpp.o

.PHONY : MPCSolver.o

# target to build an object file
MPCSolver.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/MPCSolver.cpp.o
.PHONY : MPCSolver.cpp.o

MPCSolver.i: MPCSolver.cpp.i

.PHONY : MPCSolver.i

# target to preprocess a source file
MPCSolver.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/MPCSolver.cpp.i
.PHONY : MPCSolver.cpp.i

MPCSolver.s: MPCSolver.cpp.s

.PHONY : MPCSolver.s

# target to generate assembly for a file
MPCSolver.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/MPCSolver.cpp.s
.PHONY : MPCSolver.cpp.s

NaoEventHandler.o: NaoEventHandler.cpp.o

.PHONY : NaoEventHandler.o

# target to build an object file
NaoEventHandler.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/NaoEventHandler.cpp.o
.PHONY : NaoEventHandler.cpp.o

NaoEventHandler.i: NaoEventHandler.cpp.i

.PHONY : NaoEventHandler.i

# target to preprocess a source file
NaoEventHandler.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/NaoEventHandler.cpp.i
.PHONY : NaoEventHandler.cpp.i

NaoEventHandler.s: NaoEventHandler.cpp.s

.PHONY : NaoEventHandler.s

# target to generate assembly for a file
NaoEventHandler.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/NaoEventHandler.cpp.s
.PHONY : NaoEventHandler.cpp.s

NaoWidget.o: NaoWidget.cpp.o

.PHONY : NaoWidget.o

# target to build an object file
NaoWidget.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/NaoWidget.cpp.o
.PHONY : NaoWidget.cpp.o

NaoWidget.i: NaoWidget.cpp.i

.PHONY : NaoWidget.i

# target to preprocess a source file
NaoWidget.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/NaoWidget.cpp.i
.PHONY : NaoWidget.cpp.i

NaoWidget.s: NaoWidget.cpp.s

.PHONY : NaoWidget.s

# target to generate assembly for a file
NaoWidget.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/NaoWidget.cpp.s
.PHONY : NaoWidget.cpp.s

NaoWorldNode.o: NaoWorldNode.cpp.o

.PHONY : NaoWorldNode.o

# target to build an object file
NaoWorldNode.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/NaoWorldNode.cpp.o
.PHONY : NaoWorldNode.cpp.o

NaoWorldNode.i: NaoWorldNode.cpp.i

.PHONY : NaoWorldNode.i

# target to preprocess a source file
NaoWorldNode.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/NaoWorldNode.cpp.i
.PHONY : NaoWorldNode.cpp.i

NaoWorldNode.s: NaoWorldNode.cpp.s

.PHONY : NaoWorldNode.s

# target to generate assembly for a file
NaoWorldNode.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/NaoWorldNode.cpp.s
.PHONY : NaoWorldNode.cpp.s

Utility.o: Utility.cpp.o

.PHONY : Utility.o

# target to build an object file
Utility.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/Utility.cpp.o
.PHONY : Utility.cpp.o

Utility.i: Utility.cpp.i

.PHONY : Utility.i

# target to preprocess a source file
Utility.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/Utility.cpp.i
.PHONY : Utility.cpp.i

Utility.s: Utility.cpp.s

.PHONY : Utility.s

# target to generate assembly for a file
Utility.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/Utility.cpp.s
.PHONY : Utility.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/main.cpp.s
.PHONY : main.cpp.s

qpOASES/BLASReplacement.o: qpOASES/BLASReplacement.cpp.o

.PHONY : qpOASES/BLASReplacement.o

# target to build an object file
qpOASES/BLASReplacement.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/BLASReplacement.cpp.o
.PHONY : qpOASES/BLASReplacement.cpp.o

qpOASES/BLASReplacement.i: qpOASES/BLASReplacement.cpp.i

.PHONY : qpOASES/BLASReplacement.i

# target to preprocess a source file
qpOASES/BLASReplacement.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/BLASReplacement.cpp.i
.PHONY : qpOASES/BLASReplacement.cpp.i

qpOASES/BLASReplacement.s: qpOASES/BLASReplacement.cpp.s

.PHONY : qpOASES/BLASReplacement.s

# target to generate assembly for a file
qpOASES/BLASReplacement.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/BLASReplacement.cpp.s
.PHONY : qpOASES/BLASReplacement.cpp.s

qpOASES/Bounds.o: qpOASES/Bounds.cpp.o

.PHONY : qpOASES/Bounds.o

# target to build an object file
qpOASES/Bounds.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Bounds.cpp.o
.PHONY : qpOASES/Bounds.cpp.o

qpOASES/Bounds.i: qpOASES/Bounds.cpp.i

.PHONY : qpOASES/Bounds.i

# target to preprocess a source file
qpOASES/Bounds.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Bounds.cpp.i
.PHONY : qpOASES/Bounds.cpp.i

qpOASES/Bounds.s: qpOASES/Bounds.cpp.s

.PHONY : qpOASES/Bounds.s

# target to generate assembly for a file
qpOASES/Bounds.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Bounds.cpp.s
.PHONY : qpOASES/Bounds.cpp.s

qpOASES/Constraints.o: qpOASES/Constraints.cpp.o

.PHONY : qpOASES/Constraints.o

# target to build an object file
qpOASES/Constraints.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Constraints.cpp.o
.PHONY : qpOASES/Constraints.cpp.o

qpOASES/Constraints.i: qpOASES/Constraints.cpp.i

.PHONY : qpOASES/Constraints.i

# target to preprocess a source file
qpOASES/Constraints.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Constraints.cpp.i
.PHONY : qpOASES/Constraints.cpp.i

qpOASES/Constraints.s: qpOASES/Constraints.cpp.s

.PHONY : qpOASES/Constraints.s

# target to generate assembly for a file
qpOASES/Constraints.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Constraints.cpp.s
.PHONY : qpOASES/Constraints.cpp.s

qpOASES/Flipper.o: qpOASES/Flipper.cpp.o

.PHONY : qpOASES/Flipper.o

# target to build an object file
qpOASES/Flipper.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Flipper.cpp.o
.PHONY : qpOASES/Flipper.cpp.o

qpOASES/Flipper.i: qpOASES/Flipper.cpp.i

.PHONY : qpOASES/Flipper.i

# target to preprocess a source file
qpOASES/Flipper.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Flipper.cpp.i
.PHONY : qpOASES/Flipper.cpp.i

qpOASES/Flipper.s: qpOASES/Flipper.cpp.s

.PHONY : qpOASES/Flipper.s

# target to generate assembly for a file
qpOASES/Flipper.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Flipper.cpp.s
.PHONY : qpOASES/Flipper.cpp.s

qpOASES/Indexlist.o: qpOASES/Indexlist.cpp.o

.PHONY : qpOASES/Indexlist.o

# target to build an object file
qpOASES/Indexlist.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Indexlist.cpp.o
.PHONY : qpOASES/Indexlist.cpp.o

qpOASES/Indexlist.i: qpOASES/Indexlist.cpp.i

.PHONY : qpOASES/Indexlist.i

# target to preprocess a source file
qpOASES/Indexlist.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Indexlist.cpp.i
.PHONY : qpOASES/Indexlist.cpp.i

qpOASES/Indexlist.s: qpOASES/Indexlist.cpp.s

.PHONY : qpOASES/Indexlist.s

# target to generate assembly for a file
qpOASES/Indexlist.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Indexlist.cpp.s
.PHONY : qpOASES/Indexlist.cpp.s

qpOASES/LAPACKReplacement.o: qpOASES/LAPACKReplacement.cpp.o

.PHONY : qpOASES/LAPACKReplacement.o

# target to build an object file
qpOASES/LAPACKReplacement.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/LAPACKReplacement.cpp.o
.PHONY : qpOASES/LAPACKReplacement.cpp.o

qpOASES/LAPACKReplacement.i: qpOASES/LAPACKReplacement.cpp.i

.PHONY : qpOASES/LAPACKReplacement.i

# target to preprocess a source file
qpOASES/LAPACKReplacement.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/LAPACKReplacement.cpp.i
.PHONY : qpOASES/LAPACKReplacement.cpp.i

qpOASES/LAPACKReplacement.s: qpOASES/LAPACKReplacement.cpp.s

.PHONY : qpOASES/LAPACKReplacement.s

# target to generate assembly for a file
qpOASES/LAPACKReplacement.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/LAPACKReplacement.cpp.s
.PHONY : qpOASES/LAPACKReplacement.cpp.s

qpOASES/Matrices.o: qpOASES/Matrices.cpp.o

.PHONY : qpOASES/Matrices.o

# target to build an object file
qpOASES/Matrices.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Matrices.cpp.o
.PHONY : qpOASES/Matrices.cpp.o

qpOASES/Matrices.i: qpOASES/Matrices.cpp.i

.PHONY : qpOASES/Matrices.i

# target to preprocess a source file
qpOASES/Matrices.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Matrices.cpp.i
.PHONY : qpOASES/Matrices.cpp.i

qpOASES/Matrices.s: qpOASES/Matrices.cpp.s

.PHONY : qpOASES/Matrices.s

# target to generate assembly for a file
qpOASES/Matrices.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Matrices.cpp.s
.PHONY : qpOASES/Matrices.cpp.s

qpOASES/MessageHandling.o: qpOASES/MessageHandling.cpp.o

.PHONY : qpOASES/MessageHandling.o

# target to build an object file
qpOASES/MessageHandling.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/MessageHandling.cpp.o
.PHONY : qpOASES/MessageHandling.cpp.o

qpOASES/MessageHandling.i: qpOASES/MessageHandling.cpp.i

.PHONY : qpOASES/MessageHandling.i

# target to preprocess a source file
qpOASES/MessageHandling.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/MessageHandling.cpp.i
.PHONY : qpOASES/MessageHandling.cpp.i

qpOASES/MessageHandling.s: qpOASES/MessageHandling.cpp.s

.PHONY : qpOASES/MessageHandling.s

# target to generate assembly for a file
qpOASES/MessageHandling.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/MessageHandling.cpp.s
.PHONY : qpOASES/MessageHandling.cpp.s

qpOASES/OQPinterface.o: qpOASES/OQPinterface.cpp.o

.PHONY : qpOASES/OQPinterface.o

# target to build an object file
qpOASES/OQPinterface.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/OQPinterface.cpp.o
.PHONY : qpOASES/OQPinterface.cpp.o

qpOASES/OQPinterface.i: qpOASES/OQPinterface.cpp.i

.PHONY : qpOASES/OQPinterface.i

# target to preprocess a source file
qpOASES/OQPinterface.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/OQPinterface.cpp.i
.PHONY : qpOASES/OQPinterface.cpp.i

qpOASES/OQPinterface.s: qpOASES/OQPinterface.cpp.s

.PHONY : qpOASES/OQPinterface.s

# target to generate assembly for a file
qpOASES/OQPinterface.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/OQPinterface.cpp.s
.PHONY : qpOASES/OQPinterface.cpp.s

qpOASES/Options.o: qpOASES/Options.cpp.o

.PHONY : qpOASES/Options.o

# target to build an object file
qpOASES/Options.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Options.cpp.o
.PHONY : qpOASES/Options.cpp.o

qpOASES/Options.i: qpOASES/Options.cpp.i

.PHONY : qpOASES/Options.i

# target to preprocess a source file
qpOASES/Options.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Options.cpp.i
.PHONY : qpOASES/Options.cpp.i

qpOASES/Options.s: qpOASES/Options.cpp.s

.PHONY : qpOASES/Options.s

# target to generate assembly for a file
qpOASES/Options.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Options.cpp.s
.PHONY : qpOASES/Options.cpp.s

qpOASES/QProblem.o: qpOASES/QProblem.cpp.o

.PHONY : qpOASES/QProblem.o

# target to build an object file
qpOASES/QProblem.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/QProblem.cpp.o
.PHONY : qpOASES/QProblem.cpp.o

qpOASES/QProblem.i: qpOASES/QProblem.cpp.i

.PHONY : qpOASES/QProblem.i

# target to preprocess a source file
qpOASES/QProblem.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/QProblem.cpp.i
.PHONY : qpOASES/QProblem.cpp.i

qpOASES/QProblem.s: qpOASES/QProblem.cpp.s

.PHONY : qpOASES/QProblem.s

# target to generate assembly for a file
qpOASES/QProblem.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/QProblem.cpp.s
.PHONY : qpOASES/QProblem.cpp.s

qpOASES/QProblemB.o: qpOASES/QProblemB.cpp.o

.PHONY : qpOASES/QProblemB.o

# target to build an object file
qpOASES/QProblemB.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/QProblemB.cpp.o
.PHONY : qpOASES/QProblemB.cpp.o

qpOASES/QProblemB.i: qpOASES/QProblemB.cpp.i

.PHONY : qpOASES/QProblemB.i

# target to preprocess a source file
qpOASES/QProblemB.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/QProblemB.cpp.i
.PHONY : qpOASES/QProblemB.cpp.i

qpOASES/QProblemB.s: qpOASES/QProblemB.cpp.s

.PHONY : qpOASES/QProblemB.s

# target to generate assembly for a file
qpOASES/QProblemB.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/QProblemB.cpp.s
.PHONY : qpOASES/QProblemB.cpp.s

qpOASES/SQProblem.o: qpOASES/SQProblem.cpp.o

.PHONY : qpOASES/SQProblem.o

# target to build an object file
qpOASES/SQProblem.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SQProblem.cpp.o
.PHONY : qpOASES/SQProblem.cpp.o

qpOASES/SQProblem.i: qpOASES/SQProblem.cpp.i

.PHONY : qpOASES/SQProblem.i

# target to preprocess a source file
qpOASES/SQProblem.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SQProblem.cpp.i
.PHONY : qpOASES/SQProblem.cpp.i

qpOASES/SQProblem.s: qpOASES/SQProblem.cpp.s

.PHONY : qpOASES/SQProblem.s

# target to generate assembly for a file
qpOASES/SQProblem.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SQProblem.cpp.s
.PHONY : qpOASES/SQProblem.cpp.s

qpOASES/SQProblemSchur.o: qpOASES/SQProblemSchur.cpp.o

.PHONY : qpOASES/SQProblemSchur.o

# target to build an object file
qpOASES/SQProblemSchur.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SQProblemSchur.cpp.o
.PHONY : qpOASES/SQProblemSchur.cpp.o

qpOASES/SQProblemSchur.i: qpOASES/SQProblemSchur.cpp.i

.PHONY : qpOASES/SQProblemSchur.i

# target to preprocess a source file
qpOASES/SQProblemSchur.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SQProblemSchur.cpp.i
.PHONY : qpOASES/SQProblemSchur.cpp.i

qpOASES/SQProblemSchur.s: qpOASES/SQProblemSchur.cpp.s

.PHONY : qpOASES/SQProblemSchur.s

# target to generate assembly for a file
qpOASES/SQProblemSchur.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SQProblemSchur.cpp.s
.PHONY : qpOASES/SQProblemSchur.cpp.s

qpOASES/SolutionAnalysis.o: qpOASES/SolutionAnalysis.cpp.o

.PHONY : qpOASES/SolutionAnalysis.o

# target to build an object file
qpOASES/SolutionAnalysis.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SolutionAnalysis.cpp.o
.PHONY : qpOASES/SolutionAnalysis.cpp.o

qpOASES/SolutionAnalysis.i: qpOASES/SolutionAnalysis.cpp.i

.PHONY : qpOASES/SolutionAnalysis.i

# target to preprocess a source file
qpOASES/SolutionAnalysis.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SolutionAnalysis.cpp.i
.PHONY : qpOASES/SolutionAnalysis.cpp.i

qpOASES/SolutionAnalysis.s: qpOASES/SolutionAnalysis.cpp.s

.PHONY : qpOASES/SolutionAnalysis.s

# target to generate assembly for a file
qpOASES/SolutionAnalysis.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SolutionAnalysis.cpp.s
.PHONY : qpOASES/SolutionAnalysis.cpp.s

qpOASES/SparseSolver.o: qpOASES/SparseSolver.cpp.o

.PHONY : qpOASES/SparseSolver.o

# target to build an object file
qpOASES/SparseSolver.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SparseSolver.cpp.o
.PHONY : qpOASES/SparseSolver.cpp.o

qpOASES/SparseSolver.i: qpOASES/SparseSolver.cpp.i

.PHONY : qpOASES/SparseSolver.i

# target to preprocess a source file
qpOASES/SparseSolver.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SparseSolver.cpp.i
.PHONY : qpOASES/SparseSolver.cpp.i

qpOASES/SparseSolver.s: qpOASES/SparseSolver.cpp.s

.PHONY : qpOASES/SparseSolver.s

# target to generate assembly for a file
qpOASES/SparseSolver.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SparseSolver.cpp.s
.PHONY : qpOASES/SparseSolver.cpp.s

qpOASES/SubjectTo.o: qpOASES/SubjectTo.cpp.o

.PHONY : qpOASES/SubjectTo.o

# target to build an object file
qpOASES/SubjectTo.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SubjectTo.cpp.o
.PHONY : qpOASES/SubjectTo.cpp.o

qpOASES/SubjectTo.i: qpOASES/SubjectTo.cpp.i

.PHONY : qpOASES/SubjectTo.i

# target to preprocess a source file
qpOASES/SubjectTo.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SubjectTo.cpp.i
.PHONY : qpOASES/SubjectTo.cpp.i

qpOASES/SubjectTo.s: qpOASES/SubjectTo.cpp.s

.PHONY : qpOASES/SubjectTo.s

# target to generate assembly for a file
qpOASES/SubjectTo.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/SubjectTo.cpp.s
.PHONY : qpOASES/SubjectTo.cpp.s

qpOASES/Utils.o: qpOASES/Utils.cpp.o

.PHONY : qpOASES/Utils.o

# target to build an object file
qpOASES/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Utils.cpp.o
.PHONY : qpOASES/Utils.cpp.o

qpOASES/Utils.i: qpOASES/Utils.cpp.i

.PHONY : qpOASES/Utils.i

# target to preprocess a source file
qpOASES/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Utils.cpp.i
.PHONY : qpOASES/Utils.cpp.i

qpOASES/Utils.s: qpOASES/Utils.cpp.s

.PHONY : qpOASES/Utils.s

# target to generate assembly for a file
qpOASES/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/qpOASES/Utils.cpp.s
.PHONY : qpOASES/Utils.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/osgAtlasSimbicon.dir/build.make CMakeFiles/osgAtlasSimbicon.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... osgAtlasSimbicon"
	@echo "... Controller.o"
	@echo "... Controller.i"
	@echo "... Controller.s"
	@echo "... MPCSolver.o"
	@echo "... MPCSolver.i"
	@echo "... MPCSolver.s"
	@echo "... NaoEventHandler.o"
	@echo "... NaoEventHandler.i"
	@echo "... NaoEventHandler.s"
	@echo "... NaoWidget.o"
	@echo "... NaoWidget.i"
	@echo "... NaoWidget.s"
	@echo "... NaoWorldNode.o"
	@echo "... NaoWorldNode.i"
	@echo "... NaoWorldNode.s"
	@echo "... Utility.o"
	@echo "... Utility.i"
	@echo "... Utility.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... qpOASES/BLASReplacement.o"
	@echo "... qpOASES/BLASReplacement.i"
	@echo "... qpOASES/BLASReplacement.s"
	@echo "... qpOASES/Bounds.o"
	@echo "... qpOASES/Bounds.i"
	@echo "... qpOASES/Bounds.s"
	@echo "... qpOASES/Constraints.o"
	@echo "... qpOASES/Constraints.i"
	@echo "... qpOASES/Constraints.s"
	@echo "... qpOASES/Flipper.o"
	@echo "... qpOASES/Flipper.i"
	@echo "... qpOASES/Flipper.s"
	@echo "... qpOASES/Indexlist.o"
	@echo "... qpOASES/Indexlist.i"
	@echo "... qpOASES/Indexlist.s"
	@echo "... qpOASES/LAPACKReplacement.o"
	@echo "... qpOASES/LAPACKReplacement.i"
	@echo "... qpOASES/LAPACKReplacement.s"
	@echo "... qpOASES/Matrices.o"
	@echo "... qpOASES/Matrices.i"
	@echo "... qpOASES/Matrices.s"
	@echo "... qpOASES/MessageHandling.o"
	@echo "... qpOASES/MessageHandling.i"
	@echo "... qpOASES/MessageHandling.s"
	@echo "... qpOASES/OQPinterface.o"
	@echo "... qpOASES/OQPinterface.i"
	@echo "... qpOASES/OQPinterface.s"
	@echo "... qpOASES/Options.o"
	@echo "... qpOASES/Options.i"
	@echo "... qpOASES/Options.s"
	@echo "... qpOASES/QProblem.o"
	@echo "... qpOASES/QProblem.i"
	@echo "... qpOASES/QProblem.s"
	@echo "... qpOASES/QProblemB.o"
	@echo "... qpOASES/QProblemB.i"
	@echo "... qpOASES/QProblemB.s"
	@echo "... qpOASES/SQProblem.o"
	@echo "... qpOASES/SQProblem.i"
	@echo "... qpOASES/SQProblem.s"
	@echo "... qpOASES/SQProblemSchur.o"
	@echo "... qpOASES/SQProblemSchur.i"
	@echo "... qpOASES/SQProblemSchur.s"
	@echo "... qpOASES/SolutionAnalysis.o"
	@echo "... qpOASES/SolutionAnalysis.i"
	@echo "... qpOASES/SolutionAnalysis.s"
	@echo "... qpOASES/SparseSolver.o"
	@echo "... qpOASES/SparseSolver.i"
	@echo "... qpOASES/SparseSolver.s"
	@echo "... qpOASES/SubjectTo.o"
	@echo "... qpOASES/SubjectTo.i"
	@echo "... qpOASES/SubjectTo.s"
	@echo "... qpOASES/Utils.o"
	@echo "... qpOASES/Utils.i"
	@echo "... qpOASES/Utils.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

